name: physioghar
description: "PhysioGhar is a platform that connects patients with physiotherapists for home and clinic-based physiotherapy services."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  google_fonts: ^8.2.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # App images
  assets:
    - assets/images/physioghar_logo.jfif

# Native splash screen configuration
flutter_native_splash:
  color: "#FBFBF8"
  image: assets/images/physioghar_logo.jfif
  android: true
  ios: true
  web: false

  android_12:
    color: "#FBFBF8"
    image: assets/images/physioghar_logo.jfif

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/physioghar_logo.png"