name: physioghar
description: "PhysioGhar is a platform that connects patients with physiotherapists for home and clinic-based physiotherapy services."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_native_splash: ^2.4.8
  google_fonts: ^8.2.1
  flutter_launcher_icons: ^0.14.4

  flutter_secure_storage: ^11.1.1
  riverpod: ^3.4.3
  dio: ^5.11.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # App images
  assets:
    - assets/icons/
    - assets/images/


# Native splash screen configuration
flutter_native_splash:
  color: "#3F7965"
  image: assets/icons/transparent_logo.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#3F7965"
    image: assets/icons/transparent_logo.png
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/physioghar_logo.png"