name: Test Dev and Merge to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test:
    name: Test Flutter Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --debug

  merge:
    name: Merge Tested Dev into Main
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        run: |
          git fetch origin main dev
          git checkout main
          git merge origin/dev --no-edit
          git push origin mains